[package]
name = "minimint-wallet"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bincode = "1"
bitcoin = { version = "0.27.0", features = [ "rand", "serde", "bitcoinconsensus" ] }
bitcoincore-rpc = "0.14.0"
hex = "0.4.3"
itertools = "0.10.0"
minimint-api = { path = "../../minimint-api" }
minimint-derive = { path = "../../minimint-derive" }
miniscript = { version = "6.0.0", features = [ "compiler" ] }
rand = "0.6.0"
secp256k1 = { version = "0.20", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing ="0.1"